### ISSUE TITLE
Handle auth_revoked event and expire the auth parameter

### ISSUE THREAD

**Issue by bubbafat** [bubbafat/FirebaseSharp#1]

**Comment by eyasso** [comment]
Hi bubbafat,

Good job for the lib.

I have a suggestion on handling auth_revoked event. 
in Response.cs method ReadLoop(), add following code in:

//Handling of auth_revoked event
if(eventName == "auth_revoked")
{
    _cache.AuthRevoked();
}

if(read.StartsWith( "event: " ))
{
    eventName = read.Substring( 7 );
    //Add Handling of auth_revoked event
    continue;
}

This code will forward the event upwards to user (only to notify him).
Once the FirebaseSharp receives the event, the connection is closed in server.
You code gets and exception "Object reference not set to an instance of an object" null pointer.
Which causes ReadLoop() to exit.

AuthRevoked() event should be implemented like the rest of the events "Add", "Remove" and "Update". Note that we don't need to send access token because connection is closed only for current access token.

I can send the sample code.

Let me know if it helps.

**Comment by bubbafat** [comment]
Thanks for the note.

I'm doing some other refactoring in this area for offline - I put together a simple auth_revoked handler but I'm noticing that revoking a secret doesn't send an auth_revoked message.  I'm going to wait to update the nuget package because there are some breaking API changes in flight.

**Comment by bubbafat** [comment]
Code to handle auth_revoked add here:  https://github.com/bubbafat/FirebaseSharp/commit/2db36fb7295b1ea4359a03eb2896a5600cf17364

Some tests came in later.
