### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by bubbafat** [bubbafat/FirebaseSharp#7]
Look at how the cache class might be usable for this.

**Comment by bezysoftware** [comment]
When I subscribe for a node, I assume it makes a roundtrip to the firebase server to get all online data, right? If I have a custom local DB layer, is there a way to the the server to return the items which changed since the last time my app was running? (e.g. I turn of the app, someone makes changes, I turn on the app and I only get the last change)

Thanks

**Comment by bubbafat** [comment]
While the firebase protocol may (I believe does) support that, how to do it is undocumented and subject to change.  I have decided on a client-only solution to work around that.
